### PR TITLE
Implement URL History Feature in Frontend

### PR DESCRIPTION
**Pull request by samar12-rad**
Description:
This PR introduces a new feature that allows users to view their URL shortening history. Key changes include:

History Component: Created a History component that fetches stored URLs from local storage and displays them in reverse chronological order.

Animation: Implemented Framer Motion for smooth animations when URLs are added to the history.

Dark Mode Support: Integrated dark mode support to enhance the user experience based on the current theme.

Preview Functionality: Added functionality to open the shortened URL in a new tab when the "Preview" button is clicked.

Truncation of Long URLs: Implemented a utility function to truncate long URLs for better readability.

Testing:
Tested the component in both light and dark themes.
Verified that the "Preview" button correctly opens the URL in a new tab.

Notes:
This feature enhances user experience by providing easy access to previously shortened URLs.

@muruga21 Pls check #17

### CODE REVIEW

**Comment by muruga21** [comment]
@samar12-rad dude have you tried to build it on your local ?

**Comment by samar12-rad** [comment]
It was running. Let me check again

**Comment by samar12-rad** [comment]
There is one error . I am solving it

**Comment by samar12-rad** [comment]
My apologies . Can you pls check again if there is still issue in publishing ?

**Comment by muruga21** [comment]
@samar12-rad Still build faild dude

**Comment by samar12-rad** [comment]
My apologies, Not it is building fine in my locall
Their were errors . Now fixed
Try to build again pls @muruga21

**Comment by muruga21** [comment]
@samar12-rad Great.. pr merged!

**Comment by samar12-rad** [comment]
thank you @muruga21

**Pull request merged**
