### PR TITLE
Update footer with icons and improved layout

### PR DESCRIPTION
**Pull request by harish08102004**
### Summary
This PR updates the footer section by adding icons for easier contact access and improving the layout for better responsiveness.

### Details
- Added icons for **Email**, **Discord**, and **GitHub** links in the footer.
- Replaced the text links with their corresponding icons for a cleaner and modern UI.
- Ensured the layout is responsive, keeping icons aligned on different screen sizes.
- Applied hover effects to the icons for a more interactive user experience.

###Fixed Issue
#14

### CODE REVIEW

**Comment by harish08102004** [comment]
Hey @muruga21 please review it and merge it.
Additionally add labels.

**Comment by muruga21** [comment]
@harish08102004 have you tried to build it your local ?.. 
build failed in deployement..

Try to build in your local.. if you found any error.. try to fix that

**Comment by harish08102004** [comment]
Hey I'm not getting any errors.
image

**Comment by harish08102004** [comment]
Hey @muruga21 hey please check this.

**Comment by harish08102004** [comment]
Hey @muruga21 any updates ?

**Comment by muruga21** [comment]
@harish08102004 Hey harish.. im sorry man for the late review..

**Comment by muruga21** [comment]
still the build has been failed i guess.. try to build your code in local

**Comment by harish08102004** [comment]
ok let me check again.

**Comment by harish08102004** [comment]
hey @muruga21 please check now.

**Comment by harish08102004** [comment]
Hey @muruga21 can you check and give me updates ASAP

**Comment by muruga21** [comment]
@harish08102004 please attach your build success message in this pr dude..

**Comment by muruga21** [comment]
@harish08102004 if you are facing any issues.. feel free to ask

**Comment by harish08102004** [comment]
Hey I already added that commit message.

**Comment by harish08102004** [comment]
Hey @muruga21 please close this ASAP.

**Pull request merged**
