### PR TITLE
Check the function pls

### PR DESCRIPTION
**Pull request by samar12-rad**
@muruga21 , pls check the function i created, and suggest some changes. I am a little beginner in nextjs. 

I created a function saveHistory in services folder, which takes req, res and urls, and sets cookie. can you suggest me how to implement this

### CODE REVIEW

**Comment by samar12-rad** [comment]
for issue #8

**Comment by muruga21** [comment]
@samar12-rad give some time dude.. i will review it tonight

**Comment by samar12-rad** [comment]
Ok

**Comment by muruga21** [comment]
@samar12-rad just now saw your code.. could you please explain more about it.. how you approached it..?

its not a good practice to store history in cookie.. since the size of the cookie might vary from browser to browser 
For example, Microsoft Edge and IE may allow up to 180 cookies per domain,

and it might cause issue if the cookie is overloaded..

you may store a session details in the cookie

so i suggest you to store the histories in the local storage..
i hope you understand

**Comment by samar12-rad** [comment]
Okay, i understood saving urls in cookies would lead to size failure in future.

I took your suggestion and used local storage to store the urls.

Now there i created a a url list in the local storage which gets updated whenever a short url is generated. 
https://github.com/user-attachments/assets/02033157-8fd2-4418-87ab-25fa70573b98

@muruga21 , pls check.

**Comment by muruga21** [comment]
@samar12-rad great work !

**Comment by muruga21** [comment]
@samar12-rad shall i merge this pr.. or you gonna work on the frontend ?

**Comment by samar12-rad** [comment]
I want to work on the frontend. Can i create an issue for that please @muruga21 ?

**Comment by muruga21** [comment]
yup raise a new issue.. i will merger it

**Comment by samar12-rad** [comment]
I added #17 . @muruga21

**Comment by samar12-rad** [comment]
@muruga21 , in the issue you gave me lvl 3, why was it changed here to level 2?

**Comment by muruga21** [comment]
@samar12-rad bcause.. you have not implemented the frontend part right in this PR right ?.... and you gonna raise a new issue and new PR for the front end.. thats that reason

**Comment by samar12-rad** [comment]
Ok

**Comment by muruga21** [comment]
@samar12-rad marked as level 3 dude

**Comment by samar12-rad** [comment]
> @samar12-rad marked as level 3 dude... since you have worked on cookie and changed to local storage

Thank you so much

**Pull request merged**
