### PR TITLE
Use proper text above Shortened Now button

### LINKED ISSUE #84: Same text at two places in home page
**Describe the bug**
Same text at two places in home page

**To Reproduce**
1. Go to home page
2. See error

**Expected behavior**
- First text should be: Paste the URL to be shortened
- Second text should be: Your shortened URL:

**Screenshots**
tt2

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
fixes #84

### CODE REVIEW

**Comment by mehul-m-prajapati** [comment]
@muruga21 : please review it.

**Comment by muruga21** [comment]
@mehul-m-prajapati what about the requested changes dude ?

**Comment by mehul-m-prajapati** [comment]
What changes you requested? I don't see here in comments @muruga21

**Comment by muruga21** [comment]
@mehul-m-prajapati i have added in review bro.. no worries.. change the text to "Enter the URL to be shortened"

**Comment by mehul-m-prajapati** [comment]
@muruga21 : okay updated it, thanks

**Review by muruga21 — APPROVED** [review]

**Pull request merged**
