### PR TITLE
UI revamp

### LINKED ISSUE #22: Make the UI mobile responsive.
**Is your feature request related to a problem? Please describe.**
I think there are still some touchup needed in the mobile view of app.

**Describe the solution you'd like**
Altering it a bit, for perfection across all screen sizes

**Describe alternatives you've considered**
N/A

@muruga21 

image

### PR DESCRIPTION
**Pull request by ShivanshPlays**
closes #22 

image

### CODE REVIEW

**Comment by ShivanshPlays** [comment]
Screenshot 2024-10-07 022249

**Comment by muruga21** [comment]
@ShivanshPlays have you tried to build in your local ?

**Comment by muruga21** [comment]
i think build is not success

**Comment by ShivanshPlays** [comment]
Hi, can you please add the necessary tags?
gssoc-ext
gssoc
hacktoberfest
hacktoberfest-accepted
level1

**Pull request merged**
