### PR TITLE
Fixed text color bug Issue no: ##55

### PR DESCRIPTION
**Pull request by iamendless10**
Fixed the bug where the text color is initially black in color instead of white :)
Issue number: #55

### CODE REVIEW

**Comment by muruga21** [comment]
@iamendless10 can you run build in your local and attach your build success msg in this pr

**Comment by iamendless10** [comment]
image
image

**Review by muruga21 — APPROVED** [review]

**Comment by muruga21** [comment]
@iamendless10 , I appreciate your contribution to this project and look forward to your future contributions.

**Comment by iamendless10** [comment]
Yes sure @muruga21

**Pull request merged**
