### PR TITLE
Update tailwind.config.ts(Changed the theme to black and purple)

### PR DESCRIPTION
**Pull request by Bhumika-00**
Changed the theme to black and purple

### CODE REVIEW

**Comment by muruga21** [comment]
@Bhumika-00 you have done a wonder full work.. as you have created primary secondary and background colors in config file.. can you changes these colors in the code too.. so it will be helpfull to other upcoming contributors too...

**Comment by Bhumika-00** [comment]
Can you tell me I want to make change in which file as I don't know much
about react

**Comment by Bhumika-00** [comment]
I have made the changes please review.

**Comment by Bhumika-00** [comment]
Added

**Comment by Bhumika-00** [comment]
Please review

**Comment by Bhumika-00** [comment]
I have completed this

**Comment by Bhumika-00** [comment]
Thank you so much

**Comment by Bhumika-00** [comment]
This neither showing on hacktober fest nor in gssoc

**Pull request merged**
