### PR TITLE
Added Alert Box for Shortened URL and URL Highlighting

### LINKED ISSUE #4: Enhance User Experience with URL Shortening Feedback
I would like to suggest an enhancement to improve the user experience for the URL shortening feature. Currently, after a user shortens a URL, the shortened URL is displayed in a box. However, it can be easy for users to miss this information.

Proposed Solution:

Add an alert box or toast notification that clearly states, "Your shortened URL is: [shortened URL]" to immediately grab the user's attention.
Highlight the box containing the shortened URL to make it stand out, improving user recognition and ensuring the shortened URL is more noticeable.
This change will make the feature more user-friendly and ensure the shortened URL is easily identified by the user.

### PR DESCRIPTION
**Pull request by samar12-rad**
Related Issue: Resolves #4 
This PR introduces two new features to improve user experience:

Alert Box: After shortening the URL, an alert box is displayed to show the url has generated successfully, providing clear feedback.
URL Highlighting: The box containing the shortened URL is highlighted to draw attention, making it easier for users to recognize and copy the link.

Changes Made:
Added alert functionality to display the shortened URL.
Implemented visual highlighting for the shortened URL box.

Impact:
These enhancements will improve the overall user experience by offering immediate feedback and increasing visibility of the shortened URL.

@muruga21

### CODE REVIEW

**Comment by muruga21** [comment]
@samar12-rad Pr Merged !

**Comment by samar12-rad** [comment]
@muruga21 ,  Can you pls add Gssoc labels?

**Comment by muruga21** [comment]
@samar12-rad Yup added.. i thought i have added before..

**Comment by samar12-rad** [comment]
@muruga21 Thanks for adding labels, can you also add LEVEL LABEL to it?

**Comment by muruga21** [comment]
@samar12-rad yeah

**Pull request merged**
