### PR TITLE
added single deletion functionality

### PR DESCRIPTION
**Pull request by AyushSharma72**
i added a cross icon by which a single url can be deleted 
Screenshot (232)

**also added an api which mark the deleted url field as true**
Screenshot 2024-10-14 112425

**please add gssoc-ext and level3 before merge**

### CODE REVIEW

**Comment by muruga21** [comment]
@AyushSharma72 great work man.. The ui needs some improvements.. can you add a button next to preview with delete icon background red color..
i feel like the cross icon is not user friendly right now.. and i need and pop it should ask like "do you really need to delete this url"... with two button delete and cancel..

please try to add this changes i will add it as label 3 once the work is done dude..

thanks

**Comment by AyushSharma72** [comment]
> @AyushSharma72 great work man.. The ui needs some improvements.. can you add a button next to preview with delete icon background red color.. i feel like the cross icon is not user friendly right now.. and i need and pop it should ask like "do you really need to delete this url"... with two button delete and cancel..
> 
> please try to add this changes i will add the labels once the work is done dude..
> 
> thanks

Yes fine I will do it

**Comment by AyushSharma72** [comment]
hey bro check this i added the delete button not inside the button as i was confuse what to do if you want to change tell me 

delete icon:
Screenshot (245)

modal:
Screenshot (244)

**Comment by muruga21** [comment]
@AyushSharma72 yeah ayush great work..  one more thing.. can you run build in your local and attach the sceen shot here..

i will be more help full to me

**Comment by AyushSharma72** [comment]
> @AyushSharma72 yeah ayush great work.. one more thing.. can you run build in your local and attach the sceen shot here..
> 
> i will be more help full to me

I don't understand you want me to run the command 
npm run build and build the application??

**Comment by muruga21** [comment]
@AyushSharma72  npm run build dude.. make sure the application has no issue while building in production

**Comment by AyushSharma72** [comment]
> @AyushSharma72 npm run build dude.. make sure the application has no issue while building in production

Okay 👍

**Comment by AyushSharma72** [comment]
> @AyushSharma72 npm run build dude.. make sure the application has no issue while building in production

next folder after build
image

command:
Screenshot (257)

Screenshot (256)

@muruga21

**Comment by muruga21** [comment]
@AyushSharma72 great man

**Comment by AyushSharma72** [comment]
> @AyushSharma72 great man

**hey bro you did not assigned any labels to this PR it is not showing on my Gssoc leaderboard please 
add gssoc-ext and level3**

**Comment by muruga21** [comment]
@AyushSharma72 yeah man.. im sorry actually i forgot.. i have added now

**Comment by AyushSharma72** [comment]
> @AyushSharma72 yeah man.. im sorry actually i forgot.. i have added now

But bro you mentioned level3 in the issue 😅

**Pull request merged**
